apiVersion: extensions/v1beta1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend
  namespace: production
spec:
  scaleRef:
    kind: DeploymentConfig
    name: myapp
    apiVersion: v1
    subresource: scale
  minReplicas: 2
  maxReplicas: 10
  cpuUtilization:
    targetPercentage: 80
