apiVersion: v1
kind: BuildConfig
metadata:
  name: basic-pipeline
  labels:
    name: basic-pipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "myapp", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  triggers:
    - type: GitHub
      github:
        secret: secret101
    - type: Generic
      generic:
        secret: secret101
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: >-
        node('maven') {

            stage 'Development - Build'

            openshiftBuild(namespace: '${env.DEV_ENV}', buildConfig: 'myapp',
            showBuildLogs: 'true')


            stage 'Development - Deploy'

            openshiftDeploy(namespace: '${env.DEV_ENV}'', deploymentConfig: 'myapp')

            openshiftScale(namespace: '${env.DEV_ENV}'', deploymentConfig:
            'myapp',replicaCount: '1')

            stage 'Test - Deploy'

            openshiftTag(namespace: '${env.DEV_ENV}'', sourceStream: 'myapp',
            sourceTag: 'latest', destinationStream: 'myapp', destinationTag:
            'promoteToQA')

            openshiftDeploy(namespace: '${env.TEST_ENV}'', deploymentConfig: 'myapp')

            openshiftScale(namespace: '${env.TEST_ENV}', deploymentConfig:
            'myapp',replicaCount: '2')

        }
      env:
        - name: "DEV_ENV"
          value: ""
        - name: "TEST_ENV"
          value: ""
  output: {}
  resources: {}
  postCommit: {}
